version: '3'
services:
  api:
    image: swarm-town
    build: .
    networks:
      - backend
    ports:
      - "8080:8080"
    volumes:
      - ./:/usr/src/app/server

networks:
  backend:
    driver: bridge
